# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1
  codecov: codecov/codecov@3.2.2

jobs:
  build-and-test:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Webpack build for test
          command: npm run build:test
      - run:
          name: Run tests with nyc
          command: npm run coverage:test
      - run:
          name: Webpack build for dev
          command: npm run build:dev
      - run:
          name: Webpack build for production
          command: npm run build:prod
      - run:
          name: Report coverage
          command: npm run coverage:report

workflows:
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  main-workflow:
    jobs:
      - build-and-test:
          # https://circleci.com/developer/orbs/orb/codecov/codecov
          post-steps:
            - codecov/upload
